/**
 * Enemy fight facts — HP and the intent table for the things that kill you.
 *
 * src/data/enemies.json is generated by scripts/fetch-enemy-data.mjs from the
 * wiki's Lua enemy modules. Two ascension rules matter to these numbers and
 * both come from lib/ascension.ts: A8 makes enemies harder to kill (the
 * ascHp column) and A9 makes their attacks deadlier (the "N at A9+" clauses
 * already folded into intent text by the fetch script).
 *
 * RESOLUTION is the hard part. Run files name ENCOUNTERS ("Knights",
 * "Slimes") while the wiki keys individual MONSTERS ("Flail Knight",
 * "Leaf Slime (M)"), so an encounter resolves to a roster of one or more
 * members. Anything unresolvable returns undefined and callers fall back to
 * the player's own record — never a guess about a fight we can't name.
 */
import enemiesJson from '../data/enemies.json';
import { displayName } from './idFormat';

export interface EnemyIntent {
  name: string;
  text: string;
}

export interface EnemyInfo {
  name: string;
  type?: string;
  /** raw wiki HP, which may be a range: "45-48" */
  hp?: string;
  ascHp?: string;
  act?: number;
  startsWith?: string;
  party?: string;
  intents?: EnemyIntent[];
}

const ENEMIES = enemiesJson as Record<string, EnemyInfo>;

/** Enemies get tougher at A8, deadlier at A9 — see ASCENSION_RULES. */
export const ASC_HP_LEVEL = 8;

const ENCOUNTER_SUFFIX = /_(WEAK|NORMAL|ELITE|BOSS|EVENT_ENCOUNTER)$/;

/**
 * Group encounters the game names in the plural, mapped to the wiki's member
 * entries. Curated because the pluralization is not mechanical: "The Kin" is
 * a priest and its followers, "Knights" is a named gang entry.
 */
const ENCOUNTER_MEMBERS: Record<string, string[]> = {
  KNIGHTS: ['KNIGHT_GANG', 'FLAIL_KNIGHT', 'SPECTRAL_KNIGHT', 'MAGI_KNIGHT'],
  THE_KIN: ['KIN_PRIEST', 'KIN_FOLLOWER'],
  THE_LOST_AND_FORGOTTEN: ['THE_LOST', 'THE_FORGOTTEN'],
  RUBY_RAIDERS: ['ASSASSIN_RAIDER', 'AXE_RAIDER', 'BRUTE_RAIDER', 'CROSSBOW_RAIDER', 'TRACKER_RAIDER'],
  SLIMES: ['LEAF_SLIME_M', 'LEAF_SLIME_S', 'TWIG_SLIME_M', 'TWIG_SLIME_S'],
  CULTISTS: ['CALCIFIED_CULTIST', 'DAMP_CULTIST'],
  CONSTRUCT_MENAGERIE: ['PUNCH_CONSTRUCT', 'CUBEX_CONSTRUCT'],
  BOWLBUGS: ['BOWLBUG_ROCK', 'BOWLBUG_SILK', 'BOWLBUG_NECTAR', 'BOWLBUG_EGG'],
  TEST_SUBJECT: ['TEST_SUBJECT', 'TEST_SUBJECT_PHASE_2', 'TEST_SUBJECT_PHASE_3'],
};

/** Single monsters whose game id spells the name differently than the wiki. */
const MONSTER_ALIASES: Record<string, string> = {
  ASSASSIN_RUBY_RAIDER: 'ASSASSIN_RAIDER',
  AXE_RUBY_RAIDER: 'AXE_RAIDER',
  BRUTE_RUBY_RAIDER: 'BRUTE_RAIDER',
  CROSSBOW_RUBY_RAIDER: 'CROSSBOW_RAIDER',
  TRACKER_RUBY_RAIDER: 'TRACKER_RAIDER',
  // the plural sits mid-name, where singular() cannot see it
  SCROLLS_OF_BITING: 'SCROLL_OF_BITING',
};

/** Bare entity name from an ENCOUNTER.* / MONSTER.* id. */
export function bareId(id: string): string {
  const bare = id.includes('.') ? id.slice(id.indexOf('.') + 1) : id;
  return id.startsWith('ENCOUNTER.') ? bare.replace(ENCOUNTER_SUFFIX, '') : bare;
}

/** "INKLETS" -> "INKLET", "SLIMES" -> "SLIME". Plural groups only. */
function singular(base: string): string | undefined {
  if (base.endsWith('IES')) return `${base.slice(0, -3)}Y`;
  if (base.endsWith('ES') && ENEMIES[base.slice(0, -2)]) return base.slice(0, -2);
  if (base.endsWith('S') && !base.endsWith('SS')) return base.slice(0, -1);
  return undefined;
}

/** Fight facts for a single monster id. */
export function enemyInfo(id: string): EnemyInfo | undefined {
  const base = bareId(id);
  const aliased = MONSTER_ALIASES[base] ?? base;
  if (ENEMIES[aliased]) return ENEMIES[aliased];
  const one = singular(aliased);
  return one ? ENEMIES[one] : undefined;
}

export interface Dossier {
  /** display name for the encounter as the run file names it */
  name: string;
  /** every wiki entry this encounter resolves to, in fight order */
  members: EnemyInfo[];
  /** 'boss' | 'elite' | 'monster' from the members, when they agree */
  type?: string;
  /** combined HP at this ascension, when every member has a number */
  totalHp?: number;
  /** true when the encounter is a group of several monsters */
  isGroup: boolean;
}

/** Lowest number in a wiki HP cell ("45-48" -> 45); undefined when unparsable. */
function hpLow(cell: string | undefined): number | undefined {
  if (!cell) return undefined;
  const m = cell.match(/\d+/);
  return m ? Number(m[0]) : undefined;
}

/** HP for one member at an ascension — the ascHp column from A8 up. */
export function memberHp(info: EnemyInfo, ascension: number): number | undefined {
  return hpLow(ascension >= ASC_HP_LEVEL ? (info.ascHp ?? info.hp) : info.hp);
}

/**
 * Everything known about an encounter: its roster and combined HP. Returns
 * undefined when the id resolves to nothing — Kaiser Crab, for one, is not on
 * the wiki, and an empty dossier is better than an invented one.
 */
export function dossier(id: string, ascension = 0): Dossier | undefined {
  const base = bareId(id);
  const memberIds = ENCOUNTER_MEMBERS[base];
  const members = memberIds
    ? memberIds.map((m) => ENEMIES[m]).filter((m): m is EnemyInfo => Boolean(m))
    : [enemyInfo(id)].filter((m): m is EnemyInfo => Boolean(m));
  if (members.length === 0) return undefined;

  // A group entry (Knight Gang) carries the roster but no HP of its own, so
  // it must not drag the total to "unknown" — count only members that fight.
  const fighters = members.filter((m) => m.hp);
  const hps = fighters.map((m) => memberHp(m, ascension));
  const totalHp = hps.length && hps.every((h) => h !== undefined) ? hps.reduce((a, h) => a + h!, 0) : undefined;

  const types = new Set(members.map((m) => m.type).filter(Boolean));
  return {
    name: members.length === 1 ? members[0].name : displayName(id),
    members,
    type: types.size === 1 ? [...types][0] : members.find((m) => m.type === 'Boss' || m.type === 'Elite')?.type,
    totalHp,
    isGroup: members.length > 1,
  };
}

/** The single hardest-hitting intent line, for a one-line "what it does". */
export function biggestHit(d: Dossier): EnemyIntent | undefined {
  let best: { intent: EnemyIntent; dmg: number } | undefined;
  for (const m of d.members) {
    for (const intent of m.intents ?? []) {
      const dmg = intentDamage(intent.text);
      if (dmg !== undefined && (!best || dmg > best.dmg)) best = { intent, dmg };
    }
  }
  return best?.intent;
}

/**
 * Total damage an intent line threatens: "Deals 3 (4 at A9+) damage x5" is 15
 * base. Reads the BASE number so the figure matches the unascended fight; the
 * ascended value stays visible in the text itself.
 */
export function intentDamage(text: string): number | undefined {
  // "Deals 12 damage" is the house style but a handful of entries write
  // "Deal 12" — matching only the plural silently drops those intents.
  const m = text.match(/Deals?\s+(\d+)/i);
  if (!m) return undefined;
  const hits = text.match(/[x×]\s*(\d+)/i);
  return Number(m[1]) * (hits ? Number(hits[1]) : 1);
}

/**
 * The encounter's attack intents — the single definition of "this line deals
 * damage", so intentDamage, isMultiHit and every caller counting attack lines
 * agree on the same population. ("Deal"/"Deals" both occur in the data.)
 */
export function attackIntents(d: Dossier): EnemyIntent[] {
  return d.members.flatMap((m) => m.intents ?? []).filter((i) => intentDamage(i.text) !== undefined);
}

/** Attack intents that land more than once — "Deals 3 damage x5". */
export function multiHitIntents(d: Dossier): EnemyIntent[] {
  return attackIntents(d).filter((i) => /[x×]\s*\d/i.test(i.text));
}

/** True when a meaningful share of the encounter's damage arrives in swings. */
export function isMultiHit(d: Dossier): boolean {
  const lines = attackIntents(d);
  if (lines.length === 0) return false;
  return multiHitIntents(d).length / lines.length >= 0.34;
}

/**
 * Debuff names the encounter applies, deduped, in the order first seen. One
 * "Applies" can carry a whole list — "Applies 99 Frail, 99 Weak, and 99
 * Vulnerable to all players" is three debuffs, not one.
 */
export function debuffsApplied(d: Dossier): string[] {
  const out: string[] = [];
  for (const m of d.members) {
    for (const intent of m.intents ?? []) {
      for (const hit of intent.text.matchAll(/Applies\s+([^.]+)/g)) {
        const list = hit[1].split(/\s+to\s+(?:all|a|the|each)\b/)[0];
        for (const piece of list.split(/,|\s+and\s+/)) {
          const name = piece.replace(/^[\s\d]+/, '').trim();
          if (/^[A-Z]/.test(name) && !out.includes(name)) out.push(name);
        }
      }
    }
  }
  return out;
}

/** Tooltip copy: what this fight is, in one or two lines. */
export function enemyBlurb(id: string, ascension = 0): string | undefined {
  const d = dossier(id, ascension);
  if (!d) return undefined;
  const bits: string[] = [];
  if (d.totalHp) bits.push(`${d.totalHp} HP${d.isGroup ? ` across ${d.members.filter((m) => m.hp).length}` : ''}`);
  const hit = biggestHit(d);
  if (hit) bits.push(`hardest hit: ${hit.name} — ${hit.text.replace(/\.$/, '')}`);
  const debuffs = debuffsApplied(d);
  if (debuffs.length) bits.push(`applies ${debuffs.slice(0, 3).join(', ')}`);
  return bits.length ? `${bits.join('. ')}.` : undefined;
}
