/**
 * Relic and potion metadata — names, tooltip copy, rarity, and icon paths.
 *
 * src/data/relics.json and src/data/potions.json are generated by
 * scripts/fetch-item-art.mjs from the wiki's Lua data modules. Lookup is by
 * RELIC.* / POTION.* id, with a folded name match as fallback so id spelling
 * drift (a dropped THE_, an apostrophe) still resolves.
 */
import potionsJson from '../data/potions.json';
import relicsJson from '../data/relics.json';
import { displayName } from './idFormat';

export interface ItemInfo {
  name: string;
  blurb: string;
  rarity?: string;
  character?: string;
  flavor?: string;
  art?: string;
}

const RELICS = relicsJson as Record<string, ItemInfo>;
const POTIONS = potionsJson as Record<string, ItemInfo>;

/** Alphanumeric fold; a leading "the" is ignored so THE_BOOT matches Boot. */
function fold(s: string): string {
  return s
    .replace(/^(RELIC|POTION)\./, '')
    .replace(/[^a-z0-9]/gi, '')
    .toLowerCase()
    .replace(/^the/, '');
}

function foldMap(table: Record<string, ItemInfo>): Map<string, ItemInfo> {
  const map = new Map<string, ItemInfo>();
  for (const [id, info] of Object.entries(table)) {
    for (const key of [fold(id), fold(info.name)]) {
      if (!map.has(key)) map.set(key, info);
    }
  }
  return map;
}

const RELICS_BY_FOLD = foldMap(RELICS);
const POTIONS_BY_FOLD = foldMap(POTIONS);

export function relicInfo(id: string): ItemInfo | undefined {
  if (!id.startsWith('RELIC.')) return undefined;
  return RELICS[id] ?? RELICS_BY_FOLD.get(fold(id));
}

export function potionInfo(id: string): ItemInfo | undefined {
  if (!id.startsWith('POTION.')) return undefined;
  return POTIONS[id] ?? POTIONS_BY_FOLD.get(fold(id));
}

/** Display name: wiki name when known (keeps apostrophes), else prettified id. */
export function relicLabel(id: string): string {
  return relicInfo(id)?.name ?? displayName(id);
}

export function potionLabel(id: string): string {
  return potionInfo(id)?.name ?? displayName(id);
}

export function relicArt(id: string): string | undefined {
  return relicInfo(id)?.art;
}

export function potionArt(id: string): string | undefined {
  return potionInfo(id)?.art;
}

/**
 * Rarity text colors, tuned for the dark surface. The game's own read:
 * commons plain, uncommons cool, rares gold, boss red, ancients otherworldly.
 */
const RARITY_COLOR: Record<string, string> = {
  Starter: 'var(--muted)',
  Common: '#cfc4b0',
  Uncommon: '#5fb2a8',
  Rare: '#e8c060',
  Ancient: '#c060c0',
  Boss: '#d96a3e',
  Shop: '#8fae56',
  Event: '#7f9bd1',
  Special: 'var(--ink2)',
  Blight: '#8a4a3a',
};

export function rarityColor(rarity: string | undefined): string {
  if (!rarity) return 'var(--ink2)';
  const key = rarity[0].toUpperCase() + rarity.slice(1).toLowerCase();
  return RARITY_COLOR[key] ?? 'var(--ink2)';
}

/** Tooltip meta line: "Rare Relic · Ironclad", "Common Potion". */
export function itemMeta(info: ItemInfo, kind: 'relic' | 'potion'): string {
  const noun = kind === 'relic' ? 'Relic' : 'Potion';
  const base = info.rarity ? `${info.rarity} ${noun}` : noun;
  return info.character && info.character !== 'Any' ? `${base} · ${info.character}` : base;
}
