/**
 * Map-node and event copy: what a rest site, shop, chest, or named event
 * actually does. Art paths live here too so a missing event illustration
 * can fall back to the map icon without a circular import through art.ts.
 *
 * src/data/events.json is generated by scripts/fetch-place-art.mjs from the
 * wiki Lua module. Lookup is by EVENT.* id, with a folded name match so
 * EVENT.ROUND_TEA_PARTY finds the wiki's EVENT.THE_ROUND_TEA_PARTY.
 */
import eventsJson from '../data/events.json';
import { monsterArt } from './art';
import { displayName } from './idFormat';
import { restLabel, type FloorKind } from './floorLog';

export interface EventInfo {
  name: string;
  blurb: string;
  art?: string;
}

const EVENTS = eventsJson as Record<string, EventInfo>;

/** Alphanumeric fold; a leading "the" is ignored so wiki THE_X matches game X. */
export function eventFold(s: string): string {
  return s
    .replace(/^EVENT\./, '')
    .replace(/[^a-z0-9]/gi, '')
    .toLowerCase()
    .replace(/^the/, '');
}

const BY_FOLD = new Map<string, EventInfo>();
for (const [id, info] of Object.entries(EVENTS)) {
  BY_FOLD.set(eventFold(id), info);
  BY_FOLD.set(eventFold(info.name), info);
}

export function eventInfo(id: string): EventInfo | undefined {
  return EVENTS[id] ?? BY_FOLD.get(eventFold(id));
}

export function eventLabel(id: string): string {
  return eventInfo(id)?.name ?? displayName(id);
}

/** Local event illustration, only when the fetch script recorded a file. */
export function eventArt(id: string | undefined): string | undefined {
  if (!id?.startsWith('EVENT.')) return undefined;
  return eventInfo(id)?.art;
}

export function mapArt(kind: FloorKind): string {
  return `art/map/${kind.toUpperCase()}.webp`;
}

const KIND_BLURB: Record<FloorKind, string> = {
  monster: 'A hallway fight. Gold, a card pick, and sometimes a potion.',
  elite: 'A hard fight. Always a relic, plus gold and a card pick.',
  boss: 'The act boss. Rare cards and gold if you win. Act 3 is the run.',
  event: 'An unknown — usually an event, sometimes a fight, shop, or chest.',
  rest: 'Campfire. Rest to heal 30% of max HP, or smith to upgrade a card. Relics can add more options.',
  shop: 'The Merchant. Five character cards, two colorless, three relics, three potions, and one card removal.',
  treasure: 'A chest. A relic and some gold. Guaranteed at the midpoint of each act.',
};

const REST_BLURB: Record<string, string> = {
  HEAL: 'Rest. Heal for 30% of max HP (rounded down). Still available at full health.',
  SMITH: 'Smith. Upgrade one card in your deck.',
  DIG: 'Dig (Shovel). Gain a random relic.',
  COOK: 'Cook (Meat Cleaver). Remove 2 cards and gain 5 max HP.',
  HATCH: 'Hatch Byrdonis Egg. Gain Byrdpip and add Byrd Swoop to your deck.',
  LIFT: 'Train (Girya). Gain 1 Strength. Up to three uses.',
  CLONE: 'Clone. Duplicate every card in your deck that has the Clone enchantment.',
  KINDLE: 'Kindle (Pumpkin Candle). Gain 5 more charges.',
};

export function placeBlurb(kind: FloorKind, eventId?: string): string {
  if (eventId) return eventInfo(eventId)?.blurb ?? KIND_BLURB.event;
  return KIND_BLURB[kind];
}

export function restBlurb(choice: string): string {
  return REST_BLURB[choice] ?? `${restLabel(choice)}. A campfire option.`;
}

export function floorThumb(facts: { encounterId?: string; eventId?: string; kind: FloorKind }): string {
  return monsterArt(facts.encounterId) ?? eventArt(facts.eventId) ?? mapArt(facts.kind);
}

const PLACE_COLOR: Partial<Record<FloorKind, string>> = {
  event: 'var(--c-necro)',
  rest: 'var(--win)',
  shop: 'var(--c-regent)',
  treasure: 'var(--ember)',
  elite: 'var(--ember)',
  boss: 'var(--loss)',
};

export function placeColor(kind: FloorKind): string | undefined {
  return PLACE_COLOR[kind];
}
