{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 0,
  "build_id": "v0.103.3",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.INFESTED_PRISMS_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PRECISE_SCISSORS",
                "title": {
                  "key": "PRECISE_SCISSORS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "ARCANE_SCROLL",
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "LARGE_CAPSULE",
                "title": {
                  "key": "LARGE_CAPSULE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TYRANNY"
              }
            ],
            "current_gold": 99,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 75,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.ARCANE_SCROLL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.BEGONE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PARTICLE_WALL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BEGONE"
              }
            ],
            "current_gold": 114,
            "current_hp": 73,
            "damage_taken": 2,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.BYRDONIS_EGG"
              }
            ],
            "current_gold": 114,
            "current_hp": 73,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BYRDONIS_NEST.pages.INITIAL.options.TAKE.title",
                  "table": "events"
                },
                "variables": {
                  "Card": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Byrdonis Egg"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BYRDONIS_NEST",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ORBIT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PHOTON_CUT"
              }
            ],
            "current_gold": 130,
            "current_hp": 70,
            "damage_taken": 3,
            "gold_gained": 16,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KINGLY_KICK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLITTERSTREAM"
              }
            ],
            "current_gold": 148,
            "current_hp": 68,
            "damage_taken": 2,
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_S",
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.LEAF_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.BEAT_INTO_SHAPE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_REGENT"
                }
              }
            ],
            "current_gold": 148,
            "current_hp": 59,
            "damage_taken": 9,
            "event_choices": [
              {
                "title": {
                  "key": "WHISPERING_HOLLOW.pages.INITIAL.options.HUG.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WHISPERING_HOLLOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CRUSH_UNDER"
              }
            ],
            "current_gold": 163,
            "current_hp": 51,
            "damage_taken": 8,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.VINE_SHAMBLER_NORMAL",
            "monster_ids": [
              "MONSTER.VINE_SHAMBLER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.CONVERGENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROPHESIZE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CONVERGENCE"
              }
            ],
            "current_gold": 208,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_MEMORIES",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FLEX_POTION",
              "POTION.DUPLICATOR"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BEAT_INTO_SHAPE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PARRY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PANACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOSTALGIA"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.THE_SMITH"
              },
              {
                "id": "CARD.RADIATE"
              }
            ],
            "current_gold": 20,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 188,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": false
              },
              {
                "choice": "POTION.BOTTLED_POTENTIAL",
                "was_picked": false
              },
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": false
              },
              {
                "choice": "RELIC.PARRYING_SHIELD",
                "was_picked": false
              },
              {
                "choice": "RELIC.ROYAL_STAMP",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 68,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 48,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VAMBRACE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.BYRD_SWOOP"
                },
                "original_card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.BYRDONIS_EGG"
                }
              }
            ],
            "current_gold": 68,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BYRDPIP",
                "was_picked": true
              }
            ],
            "rest_site_choices": [
              "HATCH"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.REFLECT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REFLECT"
              }
            ],
            "current_gold": 79,
            "current_hp": 44,
            "damage_taken": 7,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_NORMAL",
            "monster_ids": [
              "MONSTER.NIBBIT",
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 79,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.REFLECT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 79,
            "current_hp": 44,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TABLET_OF_TRUTH.pages.INITIAL.options.DECIPHER_1.title",
                  "table": "events"
                },
                "variables": {
                  "SmashHPGain": {
                    "type": "BaseDynamic",
                    "decimal_value": 20,
                    "bool_value": false,
                    "string_value": null
                  },
                  "DecipherMaxHpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 12,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TABLET_OF_TRUTH.pages.DECIPHER_1.options.DECIPHER.title",
                  "table": "events"
                },
                "variables": {
                  "SmashHPGain": {
                    "type": "BaseDynamic",
                    "decimal_value": 20,
                    "bool_value": false,
                    "string_value": null
                  },
                  "DecipherMaxHpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 12,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TABLET_OF_TRUTH.pages.DECIPHER.options.GIVE_UP.title",
                  "table": "events"
                },
                "variables": {
                  "SmashHPGain": {
                    "type": "BaseDynamic",
                    "decimal_value": 20,
                    "bool_value": false,
                    "string_value": null
                  },
                  "DecipherMaxHpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 12,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 9,
            "player_id": 1,
            "upgraded_cards": [
              "CARD.VENERATE",
              "CARD.GLITTERSTREAM"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TABLET_OF_TRUTH",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BEAT_INTO_SHAPE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DYING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWORD_SAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DARK_SHACKLES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MAYHEM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SUMMON_FORTH"
              }
            ],
            "current_gold": 3,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 76,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": false
              },
              {
                "choice": "RELIC.PLANISPHERE",
                "was_picked": false
              },
              {
                "choice": "RELIC.CHEMICAL_X",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 3,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.CRUSH_UNDER"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.BEAT_INTO_SHAPE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TYRANNY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NEUTRON_AEGIS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BEAT_INTO_SHAPE"
              }
            ],
            "current_gold": 103,
            "current_hp": 2,
            "damage_taken": 42,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.LIQUID_BRONZE",
              "POTION.LIQUID_MEMORIES"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_KIN_BOSS",
            "monster_ids": [
              "MONSTER.KIN_FOLLOWER",
              "MONSTER.KIN_FOLLOWER",
              "MONSTER.KIN_PRIEST"
            ],
            "room_type": "boss",
            "turns_taken": 6
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "YUMMY_COOKIE",
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "STORYBOOK",
                "title": {
                  "key": "STORYBOOK.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_COMPASS",
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 103,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 64,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.GOLDEN_COMPASS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ALIGNMENT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.STARDUST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.COLLISION_COURSE"
              }
            ],
            "current_gold": 123,
            "current_hp": 53,
            "damage_taken": 13,
            "gold_gained": 20,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 23,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RANWID_THE_ELDER.pages.INITIAL.options.GOLD.title",
                  "table": "events"
                },
                "variables": {
                  "Potion": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Colorless Potion"
                  },
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Pendulum"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.RANWID_THE_ELDER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 21,
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.CELESTIAL_MIGHT"
              }
            ],
            "current_gold": 42,
            "current_hp": 51,
            "damage_taken": 4,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_NECTAR"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 42,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.COLLISION_COURSE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 23,
                  "id": "CARD.BULWARK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RESONANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BULWARK"
              }
            ],
            "current_gold": 55,
            "current_hp": 38,
            "damage_taken": 15,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.COLORLESS_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CHOMPERS_NORMAL",
            "monster_ids": [
              "MONSTER.CHOMPER",
              "MONSTER.CHOMPER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 55,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BULWARK"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.SHARP"
                  },
                  "floor_added_to_deck": 7,
                  "id": "CARD.CRUSH_UNDER"
                },
                "enchantment": "ENCHANTMENT.SHARP"
              }
            ],
            "current_gold": 55,
            "current_hp": 38,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SELF_HELP_BOOK.pages.INITIAL.options.READ_THE_BACK.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment1": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sharp"
                  },
                  "Enchantment2": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Nimble"
                  },
                  "Enchantment3": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Swift"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SELF_HELP_BOOK",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 105,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 50,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.GLIMMER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LANTERN_KEY"
              }
            ],
            "current_gold": 117,
            "current_hp": 5,
            "damage_taken": 35,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.INITIAL.options.KEEP_THE_KEY.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.KEEP_THE_KEY.options.FIGHT.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_LANTERN_KEY",
            "room_type": "event",
            "turns_taken": 0
          },
          {
            "model_id": "ENCOUNTER.MYSTERIOUS_KNIGHT_EVENT_ENCOUNTER",
            "monster_ids": [
              "MONSTER.MYSTERIOUS_KNIGHT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 159,
            "current_hp": 5,
            "damage_taken": 0,
            "gold_gained": 42,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.RAZOR_TOOTH",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 159,
            "current_hp": 5,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DOLL_ROOM.pages.INITIAL.options.RANDOM.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.DAUGHTER_OF_THE_WIND",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.DOLL_ROOM",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.KINGLY_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THE_BOMB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOSTALGIA"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.COLLISION_COURSE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 36,
            "current_hp": 5,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 123,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FYSH_OIL",
                "was_picked": false
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TINY_MAILBOX",
                "was_picked": false
              },
              {
                "choice": "RELIC.LUNAR_PASTRY",
                "was_picked": false
              },
              {
                "choice": "RELIC.KIFUDA",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 36,
            "current_hp": 0,
            "damage_taken": 7,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.LIQUID_BRONZE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FALLING_STAR"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TYRANNY"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.BEGONE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.PHOTON_CUT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.GLITTERSTREAM"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.BEAT_INTO_SHAPE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.SHARP"
          },
          "floor_added_to_deck": 7,
          "id": "CARD.CRUSH_UNDER"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.CONVERGENCE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "CARD.THE_SMITH"
        },
        {
          "floor_added_to_deck": 9,
          "id": "CARD.RADIATE"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.BYRD_SWOOP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 12,
          "id": "CARD.REFLECT"
        },
        {
          "floor_added_to_deck": 15,
          "id": "CARD.SUMMON_FORTH"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.BEAT_INTO_SHAPE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.COLLISION_COURSE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.CELESTIAL_MIGHT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.BULWARK"
        },
        {
          "floor_added_to_deck": 27,
          "id": "CARD.LANTERN_KEY"
        },
        {
          "floor_added_to_deck": 30,
          "id": "CARD.COLLISION_COURSE"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 3,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.ARCANE_SCROLL"
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.PENDULUM",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 0
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.VAMBRACE"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.BYRDPIP",
          "props": {
            "strings": [
              {
                "name": "Skin",
                "value": "version2"
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.GOLDEN_COMPASS",
          "props": {
            "ints": [
              {
                "name": "GoldenPathAct",
                "value": 1
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.BLOOD_VIAL"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.RED_MASK"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.RAZOR_TOOTH"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.DAUGHTER_OF_THE_WIND"
        }
      ]
    }
  ],
  "run_time": 1312,
  "schema_version": 9,
  "seed": "LM4RXQBDMS",
  "start_time": 1780340842,
  "was_abandoned": false,
  "win": false
}