{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 5,
  "build_id": "v0.107.1",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.KNIGHTS_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NEW_LEAF",
                "title": {
                  "key": "NEW_LEAF.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "LOST_COFFER",
                "title": {
                  "key": "LOST_COFFER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SILKEN_TRESS",
                "title": {
                  "key": "SILKEN_TRESS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.COLD_SNAP"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_DEFECT"
                }
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NEW_LEAF.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.NEW_LEAF",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BALL_LIGHTNING"
              }
            ],
            "current_gold": 109,
            "current_hp": 53,
            "damage_taken": 7,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OVERCLOCK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ULTIMATE_DEFEND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALAMITY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.STORM"
              },
              {
                "id": "CARD.BEAM_CELL"
              }
            ],
            "current_gold": 8,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 101,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": false
              },
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PEAR",
                "was_picked": false
              },
              {
                "choice": "RELIC.TUNGSTEN_ROD",
                "was_picked": false
              },
              {
                "choice": "RELIC.DINGY_RUG",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.LIGHTNING_ROD"
              }
            ],
            "current_gold": 8,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BRAIN_LEECH.pages.INITIAL.options.SHARE_KNOWLEDGE.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BRAIN_LEECH",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.GLASSWORK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SYNTHESIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLASSWORK"
              }
            ],
            "current_gold": 21,
            "current_hp": 51,
            "damage_taken": 2,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 79,
            "current_hp": 51,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_TREASURY.pages.INITIAL.options.FIRST_CHEST.title",
                  "table": "events"
                },
                "variables": {
                  "SmallChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 58,
                    "bool_value": false,
                    "string_value": null
                  },
                  "LargeChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 304,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 58,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SUNKEN_TREASURY",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CHARGE_BATTERY"
              }
            ],
            "current_gold": 94,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SNECKO_OIL",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 94,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.LIGHTNING_ROD"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 9,
                  "id": "CARD.SYNCHRONIZE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SYNCHRONIZE"
              }
            ],
            "current_gold": 122,
            "current_hp": 43,
            "damage_taken": 8,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.DEXTERITY_POTION",
              "POTION.SNECKO_OIL"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.WHITE_STAR",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 156,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LANTERN",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 156,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.SYNCHRONIZE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DISCOVERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THE_GAMBIT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SUBROUTINE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 3,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 153,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": false
              },
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": false
              },
              {
                "choice": "RELIC.MYSTIC_LIGHTER",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.SWIFT"
                  },
                  "floor_added_to_deck": 12,
                  "id": "CARD.SUBROUTINE"
                },
                "enchantment": "ENCHANTMENT.SWIFT"
              }
            ],
            "current_gold": 3,
            "current_hp": 43,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SELF_HELP_BOOK.pages.INITIAL.options.READ_ENTIRE_BOOK.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment1": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sharp"
                  },
                  "Enchantment2": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Nimble"
                  },
                  "Enchantment3": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Swift"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SELF_HELP_BOOK",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.CALTROPS"
              }
            ],
            "current_gold": 103,
            "current_hp": 43,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRASH_HEAP.pages.INITIAL.options.GRAB.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TRASH_HEAP",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 15,
                  "id": "CARD.BUFFER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 15,
                  "id": "CARD.TRASH_TO_TREASURE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ALL_FOR_ONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CREATIVE_AI"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BUFFER"
              },
              {
                "id": "CARD.TRASH_TO_TREASURE"
              }
            ],
            "current_gold": 136,
            "current_hp": 42,
            "damage_taken": 1,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.KUSARIGAMA",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SKULKING_COLONY_ELITE",
            "monster_ids": [
              "MONSTER.SKULKING_COLONY"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 136,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.TRASH_TO_TREASURE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.MACHINE_LEARNING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HELIX_DRILL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BUFFER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MACHINE_LEARNING"
              }
            ],
            "current_gold": 211,
            "current_hp": 12,
            "damage_taken": 30,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.POWDERED_DEMISE"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.WATERFALL_GIANT_BOSS",
            "monster_ids": [
              "MONSTER.WATERFALL_GIANT"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_HORN",
                "title": {
                  "key": "PAELS_HORN.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_GROWTH",
                "title": {
                  "key": "PAELS_GROWTH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_LEGION",
                "title": {
                  "key": "PAELS_LEGION.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 211,
            "current_hp": 62,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_LEGION.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 50,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_LEGION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PAEL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 19,
                  "id": "CARD.SCRAPE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.GLASSWORK"
              },
              {
                "current_upgrade_level": 1,
                "id": "CARD.SCRAPE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.GLASSWORK"
              }
            ],
            "current_gold": 222,
            "current_hp": 51,
            "damage_taken": 11,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 222,
            "current_hp": 46,
            "damage_taken": 5,
            "event_choices": [
              {
                "title": {
                  "key": "DOLL_ROOM.pages.INITIAL.options.TAKE_SOME_TIME.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "MR_STRUGGLES.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.MR_STRUGGLES",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.DOLL_ROOM",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.RUNIC_CAPACITOR"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NULL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FUSION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IMPATIENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOSTALGIA"
                },
                "was_picked": false
              }
            ],
            "current_gold": 39,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 183,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.GIGANTIFICATION_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RUNIC_CAPACITOR",
                "was_picked": true
              },
              {
                "choice": "RELIC.VAMBRACE",
                "was_picked": false
              },
              {
                "choice": "RELIC.TINY_MAILBOX",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 22,
                  "id": "CARD.TURBO"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DOUBLE_ENERGY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.TURBO"
              }
            ],
            "current_gold": 46,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OVERCLOCK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREP_TIME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALAMITY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CLAW"
              }
            ],
            "current_gold": 22,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 24,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_MEMORIES",
                "was_picked": false
              },
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ART_OF_WAR",
                "was_picked": false
              },
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": false
              },
              {
                "choice": "RELIC.KIFUDA",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 22,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.SUBROUTINE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 25,
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOTFIX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 25,
                  "id": "CARD.CREATIVE_AI"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MACHINE_LEARNING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HELIX_DRILL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BOOST_AWAY"
              },
              {
                "id": "CARD.CREATIVE_AI"
              }
            ],
            "current_gold": 52,
            "current_hp": 25,
            "damage_taken": 21,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 88,
            "current_hp": 25,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 27,
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GLASSWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOOT_SEQUENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 27,
                  "id": "CARD.SPINNER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEFRAGMENT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MULTI_CAST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.BOOST_AWAY"
              },
              {
                "id": "CARD.SPINNER"
              }
            ],
            "current_gold": 117,
            "current_hp": 25,
            "damage_taken": 14,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 14,
            "max_hp": 89,
            "max_hp_gained": 14,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BLOCK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MANGO",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              }
            ],
            "current_gold": 126,
            "current_hp": 19,
            "damage_taken": 6,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 89,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.COLORLESS_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_NORMAL",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_SILK",
              "MONSTER.BOWLBUG_EGG",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 126,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 26,
            "max_hp": 89,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 161,
            "current_hp": 45,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "COLOSSAL_FLOWER.pages.INITIAL.options.EXTRACT_CURRENT_PRIZE_1.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 89,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.COLOSSAL_FLOWER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 192,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 89,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 192,
            "current_hp": 71,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 26,
            "max_hp": 89,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.METEOR_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ADAPTIVE_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ALL_FOR_ONE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.METEOR_STRIKE"
              }
            ],
            "current_gold": 267,
            "current_hp": 67,
            "damage_taken": 4,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 89,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.VULNERABLE_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
            "monster_ids": [
              "MONSTER.THE_INSATIABLE",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "SAI",
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "WAR_HAMMER",
                "title": {
                  "key": "WAR_HAMMER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "IRON_CLUB",
                "title": {
                  "key": "IRON_CLUB.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 267,
            "current_hp": 84,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "IRON_CLUB.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 17,
            "max_hp": 89,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.IRON_CLUB",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 35,
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GUNK_UP"
              }
            ],
            "current_gold": 280,
            "current_hp": 74,
            "damage_taken": 10,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 4,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 36,
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SKIM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CHARGE_BATTERY"
              }
            ],
            "current_gold": 294,
            "current_hp": 74,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 294,
            "current_hp": 74,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BATTLEWORN_DUMMY.pages.INITIAL.options.SETTING_2.title",
                  "table": "events"
                },
                "variables": {
                  "Setting1Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 75,
                    "bool_value": false,
                    "string_value": null
                  },
                  "Setting2Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 150,
                    "bool_value": false,
                    "string_value": null
                  },
                  "Setting3Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 300,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.COLORLESS_POTION"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.STRIKE_DEFECT",
              "CARD.COLD_SNAP"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BATTLEWORN_DUMMY",
            "room_type": "event",
            "turns_taken": 0
          },
          {
            "model_id": "ENCOUNTER.BATTLEWORN_DUMMY_EVENT_ENCOUNTER",
            "monster_ids": [
              "MONSTER.BATTLE_FRIEND_V2",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.GLASSWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCAVENGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUNDER"
                },
                "was_picked": false
              }
            ],
            "current_gold": 308,
            "current_hp": 59,
            "damage_taken": 15,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FABRICATOR_NORMAL",
            "monster_ids": [
              "MONSTER.FABRICATOR",
              "MONSTER.PAELS_LEGION",
              "MONSTER.NOISEBOT",
              "MONSTER.STABBOT",
              "MONSTER.ZAPBOT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.BRONZE_SCALES"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCRAPE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLACIER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PANIC_BUTTON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ALCHEMIZE"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_DEFECT"
              }
            ],
            "current_gold": 19,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 289,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.MAZALETHS_GIFT",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              },
              {
                "choice": "RELIC.AKABEKO",
                "was_picked": false
              },
              {
                "choice": "RELIC.TOOLBOX",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 40,
                  "id": "CARD.HAILSTORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GLASSWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CHAOS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HAILSTORM"
              }
            ],
            "current_gold": 31,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CONSTRUCT_MENAGERIE_NORMAL",
            "monster_ids": [
              "MONSTER.PUNCH_CONSTRUCT",
              "MONSTER.CUBEX_CONSTRUCT",
              "MONSTER.CUBEX_CONSTRUCT",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 62,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 42,
                  "id": "CARD.GLACIER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GENETIC_ALGORITHM",
                  "props": {
                    "ints": [
                      {
                        "name": "CurrentBlock",
                        "value": 1
                      },
                      {
                        "name": "IncreasedBlock",
                        "value": 0
                      }
                    ]
                  }
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUBROUTINE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 42,
                  "id": "CARD.ECHO_FORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HYPERBEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ALL_FOR_ONE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLACIER"
              },
              {
                "id": "CARD.ECHO_FORM"
              }
            ],
            "current_gold": 92,
            "current_hp": 42,
            "damage_taken": 17,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GOLD_PLATED_CABLES",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
            "monster_ids": [
              "MONSTER.SOUL_NEXUS",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 92,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.ECHO_FORM"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 92,
            "current_hp": 0,
            "damage_taken": 42,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.STRENGTH_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNIGHTS_ELITE",
            "monster_ids": [
              "MONSTER.FLAIL_KNIGHT",
              "MONSTER.SPECTRAL_KNIGHT",
              "MONSTER.MAGI_KNIGHT",
              "MONSTER.PAELS_LEGION"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "ELITE",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.COLD_SNAP"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.BALL_LIGHTNING"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.STORM"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.BEAM_CELL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 4,
          "id": "CARD.LIGHTNING_ROD"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.CHARGE_BATTERY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 9,
          "id": "CARD.SYNCHRONIZE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.SWIFT"
          },
          "floor_added_to_deck": 12,
          "id": "CARD.SUBROUTINE"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.CALTROPS"
        },
        {
          "floor_added_to_deck": 15,
          "id": "CARD.BUFFER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 15,
          "id": "CARD.TRASH_TO_TREASURE"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.MACHINE_LEARNING"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.GLASSWORK"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.SCRAPE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 22,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 23,
          "id": "CARD.CLAW"
        },
        {
          "floor_added_to_deck": 25,
          "id": "CARD.BOOST_AWAY"
        },
        {
          "floor_added_to_deck": 25,
          "id": "CARD.CREATIVE_AI"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 27,
          "id": "CARD.BOOST_AWAY"
        },
        {
          "floor_added_to_deck": 27,
          "id": "CARD.SPINNER"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.METEOR_STRIKE"
        },
        {
          "floor_added_to_deck": 35,
          "id": "CARD.GUNK_UP"
        },
        {
          "floor_added_to_deck": 36,
          "id": "CARD.CHARGE_BATTERY"
        },
        {
          "floor_added_to_deck": 40,
          "id": "CARD.HAILSTORM"
        },
        {
          "floor_added_to_deck": 42,
          "id": "CARD.GLACIER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 42,
          "id": "CARD.ECHO_FORM"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.NEW_LEAF"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.WHITE_STAR"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.LANTERN"
        },
        {
          "floor_added_to_deck": 15,
          "id": "RELIC.KUSARIGAMA"
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.PAELS_LEGION",
          "props": {
            "strings": [
              {
                "name": "Skin",
                "value": "wings"
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.MR_STRUGGLES"
        },
        {
          "floor_added_to_deck": 21,
          "id": "RELIC.RUNIC_CAPACITOR"
        },
        {
          "floor_added_to_deck": 25,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 2
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 27,
          "id": "RELIC.MANGO"
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.CENTENNIAL_PUZZLE"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.IRON_CLUB",
          "props": {
            "ints": [
              {
                "name": "CardsPlayed",
                "value": 135
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.BRONZE_SCALES"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.GOLD_PLATED_CABLES"
        }
      ]
    }
  ],
  "run_time": 2767,
  "schema_version": 9,
  "seed": "UA6F3BUX4N",
  "start_time": 1784166775,
  "was_abandoned": false,
  "win": false
}