{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 3,
  "build_id": "v0.107.1",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "WINGED_BOOTS",
                "title": {
                  "key": "WINGED_BOOTS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NEOWS_TORMENT",
                "title": {
                  "key": "NEOWS_TORMENT.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NEOWS_FURY"
              }
            ],
            "current_gold": 99,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NEOWS_TORMENT.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 52,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.NEOWS_TORMENT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.PAGESTORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEATH_MARCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WISP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PAGESTORM"
              }
            ],
            "current_gold": 113,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK",
              "MONSTER.OSTY"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SEVERANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FETCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALCIFY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CATASTROPHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAND_OF_GREED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DEFY"
              },
              {
                "id": "CARD.SCOURGE"
              }
            ],
            "current_gold": 15,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 98,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.JOSS_PAPER",
                "was_picked": false
              },
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": false
              },
              {
                "choice": "RELIC.BREAD",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.COUNTDOWN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DRAIN_POWER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.COUNTDOWN"
              }
            ],
            "current_gold": 23,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER",
              "MONSTER.OSTY"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.SPIRAL"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFEND_NECROBINDER"
                },
                "enchantment": "ENCHANTMENT.SPIRAL"
              }
            ],
            "current_gold": 23,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SPIRALING_WHIRLPOOL.pages.INITIAL.options.OBSERVE.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SPIRALING_WHIRLPOOL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.WISP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLEANSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INVOKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.WISP"
              }
            ],
            "current_gold": 31,
            "current_hp": 49,
            "damage_taken": 3,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE",
              "MONSTER.OSTY"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 31,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.COUNTDOWN"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.RIGHT_HAND_HAND"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FLATTEN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEATH_MARCH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.RIGHT_HAND_HAND"
              }
            ],
            "current_gold": 44,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GREMLIN_MERC_NORMAL",
            "monster_ids": [
              "MONSTER.GREMLIN_MERC",
              "MONSTER.OSTY",
              "MONSTER.SNEAKY_GREMLIN",
              "MONSTER.FAT_GREMLIN"
            ],
            "room_type": "monster",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 9,
                  "id": "CARD.OBLIVION"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PARSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.OBLIVION"
              }
            ],
            "current_gold": 75,
            "current_hp": 29,
            "damage_taken": 20,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.STRENGTH_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL",
              "MONSTER.OSTY"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 108,
            "current_hp": 29,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LANTERN",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 108,
            "current_hp": 29,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.SCOURGE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DEBILITATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEATH_MARCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WISP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CATASTROPHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SALVO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HAUNT"
              },
              {
                "id": "CARD.AFTERLIFE"
              }
            ],
            "current_gold": 6,
            "current_hp": 29,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 102,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": false
              },
              {
                "choice": "POTION.POTION_OF_DOOM",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STONE_CALENDAR",
                "was_picked": false
              },
              {
                "choice": "RELIC.FESTIVE_POPPER",
                "was_picked": false
              },
              {
                "choice": "RELIC.LEES_WAFFLE",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 6,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.OUTMANEUVER"
              }
            ],
            "current_gold": 106,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRASH_HEAP.pages.INITIAL.options.GRAB.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TRASH_HEAP",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 15,
                  "id": "CARD.REAVE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DREDGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BORROWED_TIME"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REAVE"
              }
            ],
            "current_gold": 136,
            "current_hp": 16,
            "damage_taken": 32,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.NUNCHAKU",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.OSTY"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 136,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.CALL_OF_THE_VOID"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REAPER_FORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ERADICATE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CALL_OF_THE_VOID"
              }
            ],
            "current_gold": 211,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LAGAVULIN_MATRIARCH_BOSS",
            "monster_ids": [
              "MONSTER.LAGAVULIN_MATRIARCH",
              "MONSTER.OSTY"
            ],
            "room_type": "boss",
            "turns_taken": 8
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PANDORAS_BOX",
                "title": {
                  "key": "PANDORAS_BOX.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "ASTROLABE",
                "title": {
                  "key": "ASTROLABE.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "DUSTY_TOME",
                "title": {
                  "key": "DUSTY_TOME.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_transformed": [
              {
                "final_card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.DEMESNE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_NECROBINDER"
                }
              },
              {
                "final_card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_NECROBINDER"
                }
              },
              {
                "final_card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.DEATH_MARCH"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_NECROBINDER"
                }
              }
            ],
            "current_gold": 211,
            "current_hp": 59,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ASTROLABE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.ASTROLABE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.DARV",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 19,
                  "id": "CARD.COUNTDOWN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FLATTEN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.AFTERLIFE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.COUNTDOWN"
              }
            ],
            "current_gold": 222,
            "current_hp": 45,
            "damage_taken": 14,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER",
              "MONSTER.OSTY"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 222,
            "current_hp": 40,
            "damage_taken": 5,
            "event_choices": [
              {
                "title": {
                  "key": "DOLL_ROOM.pages.INITIAL.options.TAKE_SOME_TIME.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "MR_STRUGGLES.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.MR_STRUGGLES",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.DOLL_ROOM",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 222,
            "current_hp": 50,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "STONE_OF_ALL_TIME.pages.INITIAL.options.LIFT.title",
                  "table": "events"
                },
                "variables": {
                  "DrinkRandomPotion": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Strength Potion"
                  },
                  "DrinkMaxHpGain": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  },
                  "PushHpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 6,
                    "bool_value": false,
                    "string_value": null
                  },
                  "PushVigorousAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 8,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 76,
            "max_hp_gained": 10,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_discarded": [
              "POTION.STRENGTH_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.STONE_OF_ALL_TIME",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.BOOK_OF_FIVE_RINGS"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNDEATH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLEIGHT_OF_FLESH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CATASTROPHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ENTROPY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SNAP"
              }
            ],
            "current_gold": 1,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 221,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": true
              },
              {
                "choice": "RELIC.INTIMIDATING_HELMET",
                "was_picked": false
              },
              {
                "choice": "RELIC.ROYAL_STAMP",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 23,
                  "id": "CARD.DEFY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BURY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CALCIFY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DEFY"
              }
            ],
            "current_gold": 14,
            "current_hp": 13,
            "damage_taken": 37,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.ENERGY_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_EGG",
              "MONSTER.OSTY"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 14,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 25,
                  "id": "CARD.AFTERLIFE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SEANCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.AFTERLIFE"
              }
            ],
            "current_gold": 29,
            "current_hp": 32,
            "damage_taken": 3,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_OBSCURA_NORMAL",
            "monster_ids": [
              "MONSTER.THE_OBSCURA",
              "MONSTER.OSTY",
              "MONSTER.PARAFRIGHT"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 63,
            "current_hp": 32,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.HORN_CLEAT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 18,
                "id": "CARD.SCULPTING_STRIKE"
              }
            ],
            "current_gold": 63,
            "current_hp": 32,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sculpting Strike+"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SLIPPERY_BRIDGE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 63,
            "current_hp": 32,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.DEFEND_NECROBINDER"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 29,
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SCOURGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.VEILPIERCER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.GRAVE_WARDEN"
              }
            ],
            "current_gold": 90,
            "current_hp": 1,
            "damage_taken": 31,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STURDY_CLAMP",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM",
              "MONSTER.OSTY"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 30,
                  "id": "CARD.NEGATIVE_PULSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.INVOKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NEGATIVE_PULSE"
              }
            ],
            "current_gold": 98,
            "current_hp": 21,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.DEXTERITY_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CHOMPERS_NORMAL",
            "monster_ids": [
              "MONSTER.CHOMPER",
              "MONSTER.CHOMPER",
              "MONSTER.OSTY"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_potions": [
              "POTION.STRENGTH_POTION"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DEATH_MARCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FETCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NO_ESCAPE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NECRO_MASTERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PURITY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SALVO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NEGATIVE_PULSE"
              }
            ],
            "current_gold": 0,
            "current_hp": 21,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 98,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": false
              },
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": false
              },
              {
                "choice": "RELIC.PUNCH_DAGGER",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 0,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.DEMESNE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SENTRY_MODE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SACRIFICE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DEMESNE"
              }
            ],
            "current_gold": 75,
            "current_hp": 36,
            "damage_taken": 7,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.TOUCH_OF_INSANITY",
              "POTION.STRENGTH_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
            "monster_ids": [
              "MONSTER.THE_INSATIABLE",
              "MONSTER.OSTY"
            ],
            "room_type": "boss",
            "turns_taken": 8
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "DELICATE_FROND",
                "title": {
                  "key": "DELICATE_FROND.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "JEWELRY_BOX",
                "title": {
                  "key": "JEWELRY_BOX.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "BLESSED_ANTLER",
                "title": {
                  "key": "BLESSED_ANTLER.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 75,
            "current_hp": 68,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DELICATE_FROND.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 32,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.DELICATE_FROND",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NONUPEIPE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 35,
                  "id": "CARD.PULL_FROM_BELOW"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEATHS_DOOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PAGESTORM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.PULL_FROM_BELOW"
              }
            ],
            "current_gold": 86,
            "current_hp": 52,
            "damage_taken": 16,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.SPEED_POTION"
            ],
            "potion_used": [
              "POTION.SKILL_POTION",
              "POTION.BLOCK_POTION",
              "POTION.DEXTERITY_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR",
              "MONSTER.OSTY"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.SWIFT"
                  },
                  "floor_added_to_deck": 18,
                  "id": "CARD.DEMESNE"
                },
                "enchantment": "ENCHANTMENT.SWIFT"
              }
            ],
            "current_gold": 86,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SELF_HELP_BOOK.pages.INITIAL.options.READ_ENTIRE_BOOK.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment1": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sharp"
                  },
                  "Enchantment2": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Nimble"
                  },
                  "Enchantment3": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Swift"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SELF_HELP_BOOK",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 86,
            "current_hp": 41,
            "damage_taken": 11,
            "event_choices": [
              {
                "title": {
                  "key": "ROUND_TEA_PARTY.pages.INITIAL.options.PICK_FIGHT.title",
                  "table": "events"
                },
                "variables": {
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Royal Poison"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.RAINBOW_RING",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROUND_TEA_PARTY",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TIMES_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAUNT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPLASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GOLD_AXE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GRAVE_WARDEN"
              },
              {
                "id": "CARD.DEFY"
              }
            ],
            "current_gold": 12,
            "current_hp": 61,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 74,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FYSH_OIL",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": false
              },
              {
                "choice": "RELIC.PANTOGRAPH",
                "was_picked": false
              },
              {
                "choice": "RELIC.DRAGON_FRUIT",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 39,
                  "id": "CARD.AFTERLIFE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FLATTEN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.REAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.AFTERLIFE"
              }
            ],
            "current_gold": 22,
            "current_hp": 61,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SHACKLING_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.STABLE_SERUM",
                "was_picked": true
              },
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FIRE_POTION",
              "POTION.SHACKLING_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.OSTY"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 22,
            "current_hp": 61,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.PAGESTORM"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 54,
            "current_hp": 61,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 54,
            "current_hp": 61,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.NEGATIVE_PULSE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 43,
                  "id": "CARD.SCOURGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FLATTEN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.SCOURGE"
              }
            ],
            "current_gold": 80,
            "current_hp": 52,
            "damage_taken": 9,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.CLARITY",
                "was_picked": true
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.HEART_OF_IRON",
              "POTION.STABLE_SERUM",
              "POTION.CLARITY"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.SPARKLING_ROUGE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MECHA_KNIGHT_ELITE",
            "monster_ids": [
              "MONSTER.MECHA_KNIGHT",
              "MONSTER.OSTY"
            ],
            "room_type": "elite",
            "turns_taken": 9
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 80,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.CALL_OF_THE_VOID"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.RIGHT_HAND_HAND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAVEBLAST"
                },
                "was_picked": false
              }
            ],
            "current_gold": 87,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BLESSING_OF_THE_FORGE",
              "POTION.STRENGTH_POTION",
              "POTION.COLORLESS_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.AXEBOTS_NORMAL",
            "monster_ids": [
              "MONSTER.AXEBOT",
              "MONSTER.OSTY"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.RIGHT_HAND_HAND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.AFTERLIFE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COUNTDOWN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DISCOVERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANOINTED"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              }
            ],
            "current_gold": 12,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PEAR",
                "was_picked": false
              },
              {
                "choice": "RELIC.BONE_FLUTE",
                "was_picked": false
              },
              {
                "choice": "RELIC.UNDYING_SIGIL",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 12,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.DEMESNE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 12,
            "current_hp": 20,
            "damage_taken": 32,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.CURE_ALL",
                "was_picked": true
              },
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.DEXTERITY_POTION",
              "POTION.CURE_ALL",
              "POTION.ATTACK_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TEST_SUBJECT_BOSS",
            "monster_ids": [
              "MONSTER.TEST_SUBJECT",
              "MONSTER.OSTY"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "ELITE",
          "rarity": "bronze"
        },
        {
          "id": "PERFECT",
          "rarity": "bronze"
        },
        {
          "id": "SPEEDY",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.NECROBINDER",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.SPIRAL"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BODYGUARD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.UNLEASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NEOWS_FURY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.PAGESTORM"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.DEFY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.SCOURGE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 4,
          "id": "CARD.COUNTDOWN"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.WISP"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.RIGHT_HAND_HAND"
        },
        {
          "floor_added_to_deck": 9,
          "id": "CARD.OBLIVION"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.HAUNT"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.AFTERLIFE"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.OUTMANEUVER"
        },
        {
          "floor_added_to_deck": 15,
          "id": "CARD.REAVE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.CALL_OF_THE_VOID"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.SWIFT"
          },
          "floor_added_to_deck": 18,
          "id": "CARD.DEMESNE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.DEATH_MARCH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.COUNTDOWN"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.SNAP"
        },
        {
          "floor_added_to_deck": 23,
          "id": "CARD.DEFY"
        },
        {
          "floor_added_to_deck": 25,
          "id": "CARD.AFTERLIFE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 29,
          "id": "CARD.GRAVE_WARDEN"
        },
        {
          "floor_added_to_deck": 30,
          "id": "CARD.NEGATIVE_PULSE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.NEGATIVE_PULSE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.DEMESNE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 35,
          "id": "CARD.PULL_FROM_BELOW"
        },
        {
          "floor_added_to_deck": 38,
          "id": "CARD.GRAVE_WARDEN"
        },
        {
          "floor_added_to_deck": 38,
          "id": "CARD.DEFY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 39,
          "id": "CARD.AFTERLIFE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 43,
          "id": "CARD.SCOURGE"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 3,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BOUND_PHYLACTERY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.NEOWS_TORMENT"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.BRONZE_SCALES"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.LANTERN"
        },
        {
          "floor_added_to_deck": 15,
          "id": "RELIC.NUNCHAKU",
          "props": {
            "ints": [
              {
                "name": "AttacksPlayed",
                "value": 111
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.ASTROLABE"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.MR_STRUGGLES"
        },
        {
          "floor_added_to_deck": 22,
          "id": "RELIC.BOOK_OF_FIVE_RINGS",
          "props": {
            "ints": [
              {
                "name": "CardsAdded",
                "value": 12
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.HORN_CLEAT"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.STURDY_CLAMP"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.DELICATE_FROND"
        },
        {
          "floor_added_to_deck": 37,
          "id": "RELIC.RAINBOW_RING"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.PENDULUM",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 1
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.SPARKLING_ROUGE"
        }
      ]
    }
  ],
  "run_time": 2519,
  "schema_version": 9,
  "seed": "YZ9YWM3C9Q",
  "start_time": 1785768283,
  "was_abandoned": false,
  "win": true
}