{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 7,
  "build_id": "v0.107.1",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NUTRITIOUS_OYSTER",
                "title": {
                  "key": "NUTRITIOUS_OYSTER.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "NEOWS_BONES",
                "title": {
                  "key": "NEOWS_BONES.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 99,
            "current_hp": 71,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NUTRITIOUS_OYSTER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 71,
            "max_hp": 86,
            "max_hp_gained": 11,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.NUTRITIOUS_OYSTER",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BALL_LIGHTNING"
              }
            ],
            "current_gold": 111,
            "current_hp": 68,
            "damage_taken": 3,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 111,
            "current_hp": 73,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "MORPHIC_GROVE.pages.INITIAL.options.LONER.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 91,
            "max_hp_gained": 5,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.MORPHIC_GROVE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 272,
            "current_hp": 55,
            "damage_taken": 18,
            "event_choices": [
              {
                "title": {
                  "key": "JUNGLE_MAZE_ADVENTURE.pages.INITIAL.options.SOLO_QUEST.title",
                  "table": "events"
                },
                "variables": {
                  "SoloGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 161.41746,
                    "bool_value": false,
                    "string_value": null
                  },
                  "JoinForcesGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 61.50141,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 161,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.JUNGLE_MAZE_ADVENTURE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SUNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SKIM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOTFIX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PRODUCTION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCRAWL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SMOKESTACK"
              },
              {
                "id": "CARD.FTL"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 22,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 250,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.SPARKLING_ROUGE",
                "was_picked": false
              },
              {
                "choice": "RELIC.TUNING_FORK",
                "was_picked": false
              },
              {
                "choice": "RELIC.THE_ABACUS",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 22,
            "current_hp": 55,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_STATUE.pages.INITIAL.options.GRAB_SWORD.title",
                  "table": "events"
                },
                "variables": {
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sword of Stone"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 7,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.SWORD_OF_STONE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SUNKEN_STATUE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 22,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.ZAP"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.COMPACT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.COMPACT"
              }
            ],
            "current_gold": 36,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 72,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 105,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DOUBLE_ENERGY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HOLOGRAM"
              }
            ],
            "current_gold": 136,
            "current_hp": 44,
            "damage_taken": 11,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MINIATURE_CANNON",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYRDONIS_ELITE",
            "monster_ids": [
              "MONSTER.BYRDONIS"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.GLASSWORK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLASSWORK"
              }
            ],
            "current_gold": 150,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.ROCKET_PUNCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NULL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ROCKET_PUNCH"
              }
            ],
            "current_gold": 177,
            "current_hp": 37,
            "damage_taken": 7,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POWER_POTION",
              "POTION.FLEX_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BEATING_REMNANT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.STORM"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFEND_DEFECT"
                }
              }
            ],
            "current_gold": 177,
            "current_hp": 37,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "AROMA_OF_CHAOS.pages.INITIAL.options.LET_GO.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.AROMA_OF_CHAOS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 15,
                  "id": "CARD.GLACIER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COOLANT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLACIER"
              }
            ],
            "current_gold": 186,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLITHERING_STRANGLER_NORMAL",
            "monster_ids": [
              "MONSTER.SNAPPING_JAXFRUIT",
              "MONSTER.SLITHERING_STRANGLER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 186,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.REBOOT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COOLANT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.VOLTAIC"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REBOOT"
              }
            ],
            "current_gold": 261,
            "current_hp": 20,
            "damage_taken": 44,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.WEAK_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_KIN_BOSS",
            "monster_ids": [
              "MONSTER.KIN_FOLLOWER",
              "MONSTER.KIN_FOLLOWER",
              "MONSTER.KIN_PRIEST"
            ],
            "room_type": "boss",
            "turns_taken": 13
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_SOUP",
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "BIIIG_HUG",
                "title": {
                  "key": "BIIIG_HUG.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_COMPASS",
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 261,
            "current_hp": 76,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.GOLDEN_COMPASS",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CHARGE_BATTERY"
              }
            ],
            "current_gold": 268,
            "current_hp": 62,
            "damage_taken": 14,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.CLUMSY"
              }
            ],
            "current_gold": 268,
            "current_hp": 62,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.ORNATE.title",
                  "table": "events"
                },
                "variables": {
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clumsy"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THIS_OR_THAT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HAILSTORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NULL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FOCUSED_STRIKE"
              }
            ],
            "current_gold": 283,
            "current_hp": 51,
            "damage_taken": 11,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 283,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.FOCUSED_STRIKE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 23,
                  "id": "CARD.FTL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.STORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FTL"
              }
            ],
            "current_gold": 292,
            "current_hp": 50,
            "damage_taken": 1,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.COLORLESS_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_NORMAL",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 292,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.DUALCAST"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 192,
            "current_hp": 50,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WELCOME_TO_WONGOS.pages.INITIAL.options.BARGAIN_BIN.title",
                  "table": "events"
                },
                "variables": {
                  "BargainBinCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 100,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 300,
                    "bool_value": false,
                    "string_value": null
                  },
                  "FeaturedItemCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 200,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxRelicCount": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxCombatCount": {
                    "type": "BaseDynamic",
                    "decimal_value": 5,
                    "bool_value": false,
                    "string_value": null
                  },
                  "WongoPointAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 296,
                    "bool_value": false,
                    "string_value": null
                  },
                  "RemainingWongoPointAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 1704,
                    "bool_value": false,
                    "string_value": null
                  },
                  "TotalWongoBadgeAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": null
                  },
                  "RandomRelic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Art of War"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LANTERN",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WELCOME_TO_WONGOS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 231,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 27,
                  "id": "CARD.SPINNER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ADAPTIVE_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.METEOR_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SPINNER"
              }
            ],
            "current_gold": 175,
            "current_hp": 50,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "CRYSTAL_SPHERE.pages.INITIAL.options.UNCOVER_FUTURE.title",
                  "table": "events"
                },
                "variables": {
                  "UncoverFutureCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 56,
                    "bool_value": false,
                    "string_value": null
                  },
                  "UncoverFutureProphesizeCount": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "PaymentPlanCount": {
                    "type": "BaseDynamic",
                    "decimal_value": 6,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CurseTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Debt"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 56,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.CRYSTAL_SPHERE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 209,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.PERFECT_FIT"
                  },
                  "floor_added_to_deck": 21,
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "enchantment": "ENCHANTMENT.PERFECT_FIT"
              }
            ],
            "current_gold": 209,
            "current_hp": 50,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "FIELD_OF_MAN_SIZED_HOLES.pages.INITIAL.options.ENTER_YOUR_HOLE.title",
                  "table": "events"
                },
                "variables": {
                  "ResistCurse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Normality"
                  },
                  "Enchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Perfect Fit"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.FIELD_OF_MAN_SIZED_HOLES",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THUNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROLONG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALAMITY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GUNK_UP"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 20,
                "id": "CARD.CLUMSY"
              }
            ],
            "current_gold": 8,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 201,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": false
              },
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PEAR",
                "was_picked": false
              },
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": false
              },
              {
                "choice": "RELIC.DINGY_RUG",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BOOST_AWAY"
              }
            ],
            "current_gold": 36,
            "current_hp": 11,
            "damage_taken": 39,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.VULNERABLE_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 36,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.LEAP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUBROUTINE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ICE_LANCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LEAP"
              }
            ],
            "current_gold": 62,
            "current_hp": 31,
            "damage_taken": 7,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 62,
            "current_hp": 58,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 35,
                  "id": "CARD.REBOOT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUPERCRITICAL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RAINBOW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REBOOT"
              }
            ],
            "current_gold": 137,
            "current_hp": 26,
            "damage_taken": 32,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.ENERGY_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KAISER_CRAB_BOSS",
            "monster_ids": [
              "MONSTER.CRUSHER",
              "MONSTER.ROCKET"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "TANXS_WHISTLE",
                "title": {
                  "key": "TANXS_WHISTLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SAI",
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "IRON_CLUB",
                "title": {
                  "key": "IRON_CLUB.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 137,
            "current_hp": 78,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "IRON_CLUB.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 52,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.IRON_CLUB",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 37,
                  "id": "CARD.TURBO"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TURBO"
              }
            ],
            "current_gold": 151,
            "current_hp": 91,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 13,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 38,
                  "id": "CARD.HOTFIX"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HOTFIX"
              }
            ],
            "current_gold": 158,
            "current_hp": 91,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 39,
                  "id": "CARD.TESLA_COIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COMPACT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.TESLA_COIL"
              }
            ],
            "current_gold": 168,
            "current_hp": 84,
            "damage_taken": 7,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.POTION_OF_BINDING",
              "POTION.WEAK_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMED_BERSERKER_NORMAL",
            "monster_ids": [
              "MONSTER.SLIMED_BERSERKER"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 40,
                  "id": "CARD.FIGHT_THROUGH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HOTFIX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FIGHT_THROUGH"
              }
            ],
            "current_gold": 181,
            "current_hp": 65,
            "damage_taken": 19,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_LOST_AND_FORGOTTEN_NORMAL",
            "monster_ids": [
              "MONSTER.THE_LOST",
              "MONSTER.THE_FORGOTTEN"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.THINKING_AHEAD"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ETERNAL_ARMOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TURBO"
              },
              {
                "id": "CARD.THINKING_AHEAD"
              }
            ],
            "current_gold": 43,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 138,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GREMLIN_HORN",
                "was_picked": false
              },
              {
                "choice": "RELIC.DATA_DISK",
                "was_picked": false
              },
              {
                "choice": "RELIC.RUNIC_CAPACITOR",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 43,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.ROCKET_PUNCH"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 75,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PARRYING_SHIELD",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 44,
                  "id": "CARD.SMOKESTACK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SHADOW_SHIELD"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SMOKESTACK"
              }
            ],
            "current_gold": 101,
            "current_hp": 78,
            "damage_taken": 7,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SNECKO_OIL",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.SWORD_OF_JADE",
                "was_picked": true
              },
              {
                "choice": "RELIC.ETERNAL_FEATHER",
                "was_picked": true
              }
            ],
            "relics_removed": [
              "RELIC.SWORD_OF_STONE"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MECHA_KNIGHT_ELITE",
            "monster_ids": [
              "MONSTER.MECHA_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 101,
            "current_hp": 91,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 13,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.SMOKESTACK"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 46,
                  "id": "CARD.CREATIVE_AI"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SMOKESTACK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CREATIVE_AI"
              }
            ],
            "current_gold": 114,
            "current_hp": 91,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.CURE_ALL",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FABRICATOR_NORMAL",
            "monster_ids": [
              "MONSTER.FABRICATOR",
              "MONSTER.GUARDBOT",
              "MONSTER.ZAPBOT"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 47,
                  "id": "CARD.SKIM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFRACT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SKIM"
              }
            ],
            "current_gold": 144,
            "current_hp": 91,
            "damage_taken": 0,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.OROBIC_ACID",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SNECKO_OIL",
              "POTION.CURE_ALL"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNIGHTS_ELITE",
            "monster_ids": [
              "MONSTER.FLAIL_KNIGHT",
              "MONSTER.SPECTRAL_KNIGHT",
              "MONSTER.MAGI_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.FAKE_HAPPY_FLOWER",
              "RELIC.FAKE_ANCHOR",
              "RELIC.FAKE_MANGO"
            ],
            "current_gold": 4,
            "current_hp": 94,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 140,
            "gold_stolen": 0,
            "hp_healed": 3,
            "max_hp": 94,
            "max_hp_gained": 3,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.FAKE_HAPPY_FLOWER",
                "was_picked": true
              },
              {
                "choice": "RELIC.FAKE_ANCHOR",
                "was_picked": true
              },
              {
                "choice": "RELIC.FAKE_MANGO",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.FAKE_MERCHANT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 4,
            "current_hp": 94,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 94,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.CREATIVE_AI"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 4,
            "current_hp": 30,
            "damage_taken": 64,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 94,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.OROBIC_ACID"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.QUEEN_BOSS",
            "monster_ids": [
              "MONSTER.TORCH_HEAD_AMALGAM",
              "MONSTER.QUEEN"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "ELITE",
          "rarity": "silver"
        },
        {
          "id": "GLUTTON",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.BALL_LIGHTNING"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.SMOKESTACK"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.FTL"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.COMPACT"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.HOLOGRAM"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.GLASSWORK"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 13,
          "id": "CARD.ROCKET_PUNCH"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.STORM"
        },
        {
          "floor_added_to_deck": 15,
          "id": "CARD.GLACIER"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.REBOOT"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.CHARGE_BATTERY"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.PERFECT_FIT"
          },
          "floor_added_to_deck": 21,
          "id": "CARD.FOCUSED_STRIKE"
        },
        {
          "floor_added_to_deck": 23,
          "id": "CARD.FTL"
        },
        {
          "floor_added_to_deck": 27,
          "id": "CARD.SPINNER"
        },
        {
          "floor_added_to_deck": 30,
          "id": "CARD.GUNK_UP"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.BOOST_AWAY"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.LEAP"
        },
        {
          "floor_added_to_deck": 35,
          "id": "CARD.REBOOT"
        },
        {
          "floor_added_to_deck": 37,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 38,
          "id": "CARD.HOTFIX"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 39,
          "id": "CARD.TESLA_COIL"
        },
        {
          "floor_added_to_deck": 40,
          "id": "CARD.FIGHT_THROUGH"
        },
        {
          "floor_added_to_deck": 41,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 41,
          "id": "CARD.THINKING_AHEAD"
        },
        {
          "floor_added_to_deck": 44,
          "id": "CARD.SMOKESTACK"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 46,
          "id": "CARD.CREATIVE_AI"
        },
        {
          "floor_added_to_deck": 47,
          "id": "CARD.SKIM"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 4,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.NUTRITIOUS_OYSTER"
        },
        {
          "floor_added_to_deck": 44,
          "id": "RELIC.SWORD_OF_JADE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.BAG_OF_MARBLES"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.MINIATURE_CANNON"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.BEATING_REMNANT"
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.GOLDEN_COMPASS",
          "props": {
            "ints": [
              {
                "name": "GoldenPathAct",
                "value": 1
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 25,
          "id": "RELIC.LANTERN"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.BOOK_OF_FIVE_RINGS",
          "props": {
            "ints": [
              {
                "name": "CardsAdded",
                "value": 13
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.GORGET"
        },
        {
          "floor_added_to_deck": 33,
          "id": "RELIC.BRONZE_SCALES"
        },
        {
          "floor_added_to_deck": 36,
          "id": "RELIC.IRON_CLUB",
          "props": {
            "ints": [
              {
                "name": "CardsPlayed",
                "value": 230
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.PARRYING_SHIELD"
        },
        {
          "floor_added_to_deck": 44,
          "id": "RELIC.ETERNAL_FEATHER"
        },
        {
          "floor_added_to_deck": 47,
          "id": "RELIC.POTION_BELT"
        },
        {
          "floor_added_to_deck": 48,
          "id": "RELIC.FAKE_HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 2
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 48,
          "id": "RELIC.FAKE_ANCHOR"
        },
        {
          "floor_added_to_deck": 48,
          "id": "RELIC.FAKE_MANGO"
        }
      ]
    }
  ],
  "run_time": 4011,
  "schema_version": 9,
  "seed": "79NL4FQQQV",
  "start_time": 1786474978,
  "was_abandoned": false,
  "win": true
}